// 1. 定義語言字典檔
const messages = {
    'zh-Hant': {
        appTitle: '政大歷史系圖書資料庫',
        sysAdmin: '系統管理',
        loggedInStatus: '已登入',
        logout: '登出',
        searchPlaceholder: '請輸入書名或作者關鍵字...',
        loadingText: '資料載入中... 請稍候',
        noDataText: '目前沒有資料',
        noResultsText: '查無符合條件的圖書',
        itemsPerPageText: '每頁顯示筆數：',
        allText: '全部',
        totalText: '共',
        syncingText: '正在同步圖書資料...',
        detailTitle: '書籍詳細資料',
        blacklistDetailTitle: '禁借清單內容',
        edit: '編輯',
				lend_privilege: '外借權限 (即時)',
        login: '登入',
        confirm: '確認',
        close: '關閉',
        cancel: '取消',
        confirmLogout: '您確定要登出系統管理嗎？',
        submit: '送出',
        search: '查詢',
        auth: {
            username: '帳號',
            password: '密碼'
        },
        notifications: {
            notifyOnReturn: '書籍歸還時通知我'
        },
        borrowerId: '借書人代碼',
        borrowRegistrationSuccess: '登記成功！',
        borrowRegistrationFailed: '登記失敗',
        fillAllFields: '請填寫所有欄位',
        wsNotConnected: 'WebSocket 未連線。請重新整理或重新登入。',
        requestTimeout: '請求超時，未收到伺服器回應。',
        adminMenu: '管理選單',
        menu: {
            borrowRegistration: '借書登記',
            returnRegistration: '還書登記',
            newBook: '新書入庫',
            unreturnedStats: '未還統計',
            blacklist: '禁借清單',
            collectionList: '館藏清單',
            openingDays: '開館日設定',
            borrowHistory: '借閱歷史查詢',
            studentManage: '借書人帳號管理',
            adminManage: '工讀生帳號管理'
        },
        fields: {
            tno: '索書號',
            book_name: '書名',
            author: '作者',
            room: '館藏位置',
            publish: '出版社',
            year: '出版年份',
            isbn: 'ISBN',
            series: '叢書名',
            cat: '分類號',
            st_no: '借書人學號',
            department: '系所',
            email: '電子郵件',
            phone_a: '聯絡電話',
            id: '帳號',
            nickname: '暱稱',
            level: '權限等級',
            lend_time: '借出時間',
            giveback_time: '歸還時間',
            name: '姓名',
            nameRequired: '姓名 (必填)',
            category: '分類',
            fines: '罰金統計',
            reason: '原因',
            remarks: '備註',
            aumark: '作者號',
            publish_place: '出版地',
            edition: '版次',
            vol: '卷冊',
            copy: '複本',
            price: '價格',
            lend_privilege: '外借權限',
            lend: '出借狀態',
            source: '來源',
            note: '備註',
						real_lendable: '外借權限',
            real_status: '當前館藏狀態',
            expected_return: '預計歸還時間'
        },
        profile: {
            title: '個人資訊與修改密碼',
            id: '您的帳號 ID',
            nickname: '您的暱稱',
            level: '您的權限層級',
            loginIp: '最後登入 IP',
            changePassword: '修改密碼',
            passwordHint: '若不修改密碼，請將以下欄位留白即可。',
            targetId: '目標帳號 (修改他人密碼，修改自己請留白)',
            targetIdHint: 'Level 3 以上管理員專用功能',
            newPassword: '新密碼',
            confirmPassword: '確認新密碼',
            updatePassword: '更新密碼'
        },
        openday: {
            title: '開館日期設定',
            setting: '設定',
            open: '開館 (Open)',
            close: '休館 (Close)',
            mark: '標記 (Mark)',
            notePlaceholder: '備註 (如：國定假日、校慶)',
            tempSave: '暫存此日設定',
            unsavedChanges: '目前有 {count} 筆變更尚未送到伺服器。',
            selectDatePrompt: '請先從左側日曆選擇一天',
            saveAll: '儲存所有變更'
        },
        studentManage: {
            title: '借書人帳號管理',
            searchId: '輸入學號查詢',
            createNew: '新增帳號',
            update: '更新儲存',
            delete: '刪除帳號',
            confirmDelete: '確定要刪除此帳號嗎？系統將自動檢查未還書籍與罰金。',
            notFound: '查無此帳號，您可以直接填寫下方資料來新增。',
            identityType0: '測試',
            identityType1: '大學部',
            identityType2: '研究所',
            identityType3: '教職員',
            identityTypeUnknown: '未知分類',
            openProfile: '開啟借書人帳號'
        },
        adminManage: {
            title: '工讀生帳號管理',
            searchId: '輸入工讀生帳號查詢',
            passwordRequired: '新密碼 (新增或修改時必填)',
            createNew: '新增帳號',
            update: '更新儲存',
            delete: '刪除帳號',
            confirmDelete: '確定要刪除此帳號嗎？',
            notFound: '查無此帳號，您可以直接填寫下方資料來新增。'
        },
        alerts: {
            newBookRequired: '索書號與書名為必填欄位',
            newBookSuccessHint: '(3 秒後可接續輸入下一本)',
            confirmRemoveBlacklist: '確定要將學生 {stid} ({name}) 移出禁借清單嗎？',
            removeBlacklistFailed: '解除禁借失敗',
            enterNewPassword: '請輸入新密碼以進行修改',
            passwordMismatch: '兩次輸入的密碼不相符，請重新確認',
            updateFailed: '更新失敗',
            enterStudentId: '請輸入學號',
            getProfileFailed: '取得使用者資訊失敗',
            queryFailed: '查詢失敗',
            noUnreturnedBooks: '學號 {stid} 目前沒有任何未還書籍。',
            fetchOpendayTimeout: '讀取開館日資料超時',
            noChangesToSave: '目前沒有任何變更需要儲存',
            saveTimeout: '儲存超時，請稍後再試',
            opendaySaveSuccess: '開館日設定已成功更新！',
            saveFailed: '儲存失敗',
            wsDisconnectedAutoLogout: '與伺服器的 WebSocket 連線已中斷，系統已為您自動登出以保護帳號安全。',
            serverConnectionFailed: '無法連線到伺服器，請確認 Go 伺服器與 ngrok 是否執行中',
            loginFailed: '登入失敗：',
            unknownError: '未知錯誤',
            wsUrlNotSet: '請先於 Console 設定 wsUrl！',
            notReturned: '尚未歸還',
            adminRequiredFields: '帳號與暱稱為必填欄位',
            adminPasswordRequired: '新增帳號時必須設定密碼',
            pushUnsupported: '您的瀏覽器不支援推播通知功能',
            pushPermissionRequired: '需要開啟通知權限才能接收歸還通知',
            pushSubscribeSuccess: '訂閱成功！當書籍歸還時，您將會收到瀏覽器通知。',
            pushSubscribeFailed: '訂閱請求失敗，請稍後再試。',
            pushUnexpectedError: '發生錯誤，無法完成訂閱。'
        },
        footer: {
            recommendation: '※ 本網頁建議下載使用開放標準的瀏覽器或親至系圖查詢使用。',
            copyright: 'Copyright Reserved by NCCU History Department 2026'
        },
				status: {
            lendable: '可外借',
            notLendable: '不外借',
            borrowed: '已借出',
            available: '在館內'
        },
				editBook: {
            title: '編輯書籍資料',
                blacklistTitle: '編輯禁借備註',
            lendableShort: '可外借 (1)',
            notLendableShort: '不外借 (0)',
            save: '儲存變更'
        },
    },
    'en': {
        appTitle: 'NCCU History Dept. Library',
        sysAdmin: 'Admin Login',
        loggedInStatus: 'Logged In',
        logout: 'Logout',
        searchPlaceholder: 'Search by title or author...',
        loadingText: 'Loading data... Please wait',
        noDataText: 'No data available',
        noResultsText: 'No matching books found',
        itemsPerPageText: 'Rows per page:',
        allText: 'All',
        totalText: 'Total',
        syncingText: 'Syncing library data...',
        detailTitle: 'Book Details',
        blacklistDetailTitle: 'Blacklist Entry',
        edit: 'Edit',
				lend_privilege: 'Lend Privilege (Live)',
        login: 'Login',
        confirm: 'Confirm',
        close: 'Close',
        cancel: 'Cancel',
        confirmLogout: 'Are you sure you want to log out?',
        submit: 'Submit',
        search: 'Search',
        auth: {
            username: 'Username',
            password: 'Password'
        },
        notifications: {
            notifyOnReturn: 'Notify me when this book is returned'
        },
        borrowerId: 'Borrower ID',
        borrowRegistrationSuccess: 'Registration successful!',
        borrowRegistrationFailed: 'Registration failed',
        fillAllFields: 'Please fill in all fields',
        wsNotConnected: 'WebSocket is not connected. Please refresh or log in again.',
        requestTimeout: 'Request timed out without a response from the server.',
        adminMenu: 'Management',
        menu: {
            borrowRegistration: 'Borrow Registration',
            returnRegistration: 'Return Registration',
            newBook: 'New Book Entry',
            unreturnedStats: 'Unreturned Stats',
            blacklist: 'Blacklist',
            collectionList: 'Collection List',
            openingDays: 'Opening Days',
            borrowHistory: 'Borrowing History',
            studentManage: 'Student Account Management',
            adminManage: 'Staff Account Management'
        },
        fields: {
            tno: 'Call No.',
            book_name: 'Title',
            author: 'Author',
            room: 'Location',
            publish: 'Publisher',
            year: 'Year',
            isbn: 'ISBN',
            series: 'Series',
            cat: 'Category',
            st_no: 'Student ID',
            department: 'Department',
            email: 'Email',
            phone_a: 'Phone',
            id: 'Account ID',
            nickname: 'Nickname',
            level: 'Permission Level',
            lend_time: 'Borrow Time',
            giveback_time: 'Return Time',
            name: 'Name',
            nameRequired: 'Name (Required)',
            category: 'Category',
            fines: 'Fines',
            reason: 'Reason',
            remarks: 'Remarks',
            aumark: 'Author Mark',
            publish_place: 'Publication Place',
            edition: 'Edition',
            vol: 'Volume',
            copy: 'Copy',
            price: 'Price',
            lend_privilege: 'Lending Permission',
            lend: 'Lending Status',
            source: 'Source',
            note: 'Note',
						real_lendable: 'Lending Permission',
            real_status: 'Current Status',
            expected_return: 'Expected Return Time'
        },
        profile: {
            title: 'Profile & Password',
            id: 'Account ID',
            nickname: 'Nickname',
            level: 'Permission Level',
            loginIp: 'Last Login IP',
            changePassword: 'Change Password',
            passwordHint: 'Leave blank if you do not want to change your password.',
            targetId: 'Target Account (Leave blank for self)',
            targetIdHint: 'Level 3+ Admin exclusive',
            newPassword: 'New Password',
            confirmPassword: 'Confirm Password',
            updatePassword: 'Update Password'
        },
        openday: {
            title: 'Opening Days Settings',
            setting: 'Settings for',
            open: 'Open',
            close: 'Close',
            mark: 'Mark',
            notePlaceholder: 'Notes (e.g., National Holiday)',
            tempSave: 'Temporarily Save',
            unsavedChanges: 'You have {count} unsaved changes.',
            selectDatePrompt: 'Please select a date from the calendar.',
            saveAll: 'Save All Changes'
        },
        studentManage: {
            title: 'Student Account Management',
            searchId: 'Enter student ID to search',
            createNew: 'Create Account',
            update: 'Update & Save',
            delete: 'Delete Account',
            confirmDelete: 'Are you sure you want to delete this account? The system will check for unreturned books and fines.',
            notFound: 'Account not found. You can fill in the details below to create a new one.',
            identityType0: 'Test',
            identityType1: 'Undergraduate',
            identityType2: 'Graduate',
            identityType3: 'Faculty & Staff',
            identityTypeUnknown: 'Unknown category',
            openProfile: 'Open Student Profile'
        },
        adminManage: {
            title: 'Staff Account Management',
            searchId: 'Enter staff account to search',
            passwordRequired: 'New password (required when creating or updating)',
            createNew: 'Create Account',
            update: 'Update & Save',
            delete: 'Delete Account',
            confirmDelete: 'Are you sure you want to delete this account?',
            notFound: 'Account not found. You can fill in the details below to create a new one.'
        },
        alerts: {
            newBookRequired: 'Call No. and Title are required',
            newBookSuccessHint: '(You can enter the next one in 3 seconds)',
            confirmRemoveBlacklist: 'Are you sure you want to remove student {stid} ({name}) from the blacklist?',
            removeBlacklistFailed: 'Failed to remove from blacklist',
            enterNewPassword: 'Please enter a new password',
            passwordMismatch: 'Passwords do not match, please try again',
            updateFailed: 'Update failed',
            enterStudentId: 'Please enter Student ID',
            getProfileFailed: 'Failed to get profile information',
            queryFailed: 'Query failed',
            noUnreturnedBooks: 'Student {stid} has no unreturned books.',
            fetchOpendayTimeout: 'Timeout fetching opening days data',
            noChangesToSave: 'No changes to save',
            saveTimeout: 'Save timeout, please try again later',
            opendaySaveSuccess: 'Opening days successfully updated!',
            saveFailed: 'Save failed',
            wsDisconnectedAutoLogout: 'WebSocket connection lost. You have been logged out automatically.',
            serverConnectionFailed: 'Cannot connect to server. Please check if the server and ngrok are running.',
            loginFailed: 'Login failed: ',
            unknownError: 'Unknown error',
            wsUrlNotSet: 'Please set wsUrl in Console first!',
            notReturned: 'Not Returned',
            adminRequiredFields: 'Account ID and nickname are required fields',
            adminPasswordRequired: 'Password is required when creating a new account',
            pushUnsupported: 'Your browser does not support push notifications',
            pushPermissionRequired: 'Notification permission is required to receive return alerts',
            pushSubscribeSuccess: 'Subscribed successfully! You will receive a browser notification when the book is returned.',
            pushSubscribeFailed: 'Subscription request failed. Please try again later.',
            pushUnexpectedError: 'An error occurred and the subscription could not be completed.'
        },
        footer: {
            recommendation: '※ Recommended to use standard browsers or the library terminal.',
            copyright: 'Copyright Reserved by NCCU History Department 2026'
        },
				status: {
            lendable: 'Lendable',
            notLendable: 'Not Lendable',
            borrowed: 'Borrowed',
            available: 'Available'
        },
				editBook: {
            title: 'Edit Book Data',
                blacklistTitle: 'Edit Blacklist Note',
            lendableShort: 'Lendable (1)',
            notLendableShort: 'Not Lendable (0)',
            save: 'Save Changes'
        },
    },
    'ja': {
        appTitle: '政大歴史学科図書データベース',
        sysAdmin: 'システム管理',
        loggedInStatus: 'ログイン中',
        logout: 'ログアウト',
        searchPlaceholder: '書名や著者のキーワードを入力してください...',
        loadingText: 'データを読み込んでいます... お待ちください',
        noDataText: 'データがありません',
        noResultsText: '条件に一致する図書が見つかりません',
        itemsPerPageText: '1ページあたりの表示件数：',
        allText: 'すべて',
        totalText: '全',
        syncingText: '図書データを同期しています...',
        detailTitle: '書籍詳細',
        blacklistDetailTitle: '禁借リスト内容',
        edit: '編集',
				lend_privilege: '貸出権限 (即時)',
        login: 'ログイン',
        confirm: '確認',
        close: '閉じる',
        cancel: 'キャンセル',
        confirmLogout: 'システムからログアウトしてもよろしいですか？',
        submit: '送信',
        search: '検索',
        auth: {
            username: 'アカウント',
            password: 'パスワード'
        },
        notifications: {
            notifyOnReturn: 'この本が返却されたら通知する'
        },
        borrowerId: '借主ID',
        borrowRegistrationSuccess: '登録成功！',
        borrowRegistrationFailed: '登録に失敗しました',
        fillAllFields: 'すべてのフィールドに入力してください',
        wsNotConnected: 'WebSocketが接続されていません。再読み込みまたは再ログインしてください。',
        requestTimeout: 'サーバーから応答がなく、リクエストがタイムアウトしました。',
        adminMenu: '管理メニュー',
        menu: {
            borrowRegistration: '貸出登録',
            returnRegistration: '返却登録',
            newBook: '新刊登録',
            unreturnedStats: '未返却統計',
            blacklist: '利用禁止リスト',
            collectionList: '蔵書リスト',
            openingDays: '開館日設定',
            borrowHistory: '貸出履歴照会',
            studentManage: '借主アカウント管理',
            adminManage: 'スタッフアカウント管理'
        },
        fields: {
            tno: '請求記号',
            book_name: '書名',
            author: '著者',
            room: '配架場所',
            publish: '出版社',
            year: '出版年',
            isbn: 'ISBN',
            series: 'シリーズ名',
            cat: '分類番号',
            st_no: '学籍番号',
            department: '所属',
            email: 'メールアドレス',
            phone_a: '電話番号',
            id: 'アカウントID',
            nickname: 'ニックネーム',
            level: '権限レベル',
            lend_time: '貸出日時',
            giveback_time: '返却日時',
            name: '氏名',
            nameRequired: '氏名 (必須)',
            category: '区分',
            fines: '罰金',
            reason: '理由',
            remarks: '備考',
            aumark: '著者記号',
            publish_place: '出版地',
            edition: '版次',
            vol: '巻次',
            copy: '複本',
            price: '価格',
            lend_privilege: '貸出権限',
            lend: '貸出状況',
            source: '入手元',
            note: '注記',
						real_lendable: '貸出権限',
            real_status: '現在の状態',
            expected_return: '返却予定日時'
        },
        profile: {
            title: 'ユーザー情報とパスワード変更',
            id: 'アカウントID',
            nickname: 'ニックネーム',
            level: '権限レベル',
            loginIp: '最終ログインIP',
            changePassword: 'パスワード変更',
            passwordHint: 'パスワードを変更しない場合は、以下のフィールドを空白にしてください。',
            targetId: '対象アカウント (自身を変更する場合は空白)',
            targetIdHint: 'レベル3以上の管理者専用機能',
            newPassword: '新しいパスワード',
            confirmPassword: '新しいパスワード（確認）',
            updatePassword: 'パスワードを更新'
        },
        openday: {
            title: '開館日設定',
            setting: '設定',
            open: '開館 (Open)',
            close: '休館 (Close)',
            mark: 'マーク (Mark)',
            notePlaceholder: '備考 (例：祝日、創立記念日)',
            tempSave: 'この日の設定を一時保存',
            unsavedChanges: 'サーバーに送信されていない変更が {count} 件あります。',
            selectDatePrompt: '左のカレンダーから日付を選択してください',
            saveAll: 'すべての変更を保存'
        },
        studentManage: {
            title: '借主アカウント管理',
            searchId: '学籍番号で検索',
            createNew: 'アカウント作成',
            update: '更新して保存',
            delete: 'アカウント削除',
            confirmDelete: 'このアカウントを削除してもよろしいですか？システムは未返却の書籍と罰金を自動的に確認します。',
            notFound: 'アカウントが見つかりません。以下のフォームに入力して新規作成できます。',
            identityType0: 'テスト',
            identityType1: '学部生',
            identityType2: '大学院',
            identityType3: '教職員',
            identityTypeUnknown: '不明な分類',
            openProfile: '借主アカウントを開く'
        },
        adminManage: {
            title: 'スタッフアカウント管理',
            searchId: 'スタッフアカウントを入力して検索',
            passwordRequired: '新しいパスワード (新規作成・更新時は必須)',
            createNew: 'アカウント作成',
            update: '更新して保存',
            delete: 'アカウント削除',
            confirmDelete: 'このアカウントを削除してもよろしいですか？',
            notFound: 'アカウントが見つかりません。以下のフォームに入力して新規作成できます。'
        },
        alerts: {
            newBookRequired: '請求記号と書名は必須項目です',
            newBookSuccessHint: '(3秒後に次の入力を続けられます)',
            confirmRemoveBlacklist: '学生 {stid} ({name}) を利用禁止リストから削除してもよろしいですか？',
            removeBlacklistFailed: '利用禁止の解除に失敗しました',
            enterNewPassword: '変更する新しいパスワードを入力してください',
            passwordMismatch: '入力されたパスワードが一致しません。もう一度確認してください',
            updateFailed: '更新に失敗しました',
            enterStudentId: '学籍番号を入力してください',
            getProfileFailed: 'ユーザー情報の取得に失敗しました',
            queryFailed: '検索に失敗しました',
            noUnreturnedBooks: '学籍番号 {stid} に未返却の書籍はありません。',
            fetchOpendayTimeout: '開館日データの取得がタイムアウトしました',
            noChangesToSave: '保存する変更がありません',
            saveTimeout: '保存がタイムアウトしました。後でもう一度お試しください',
            opendaySaveSuccess: '開館日設定が正常に更新されました！',
            saveFailed: '保存に失敗しました',
            wsDisconnectedAutoLogout: 'サーバーとのWebSocket接続が切断されました。アカウント保護のため自動的にログアウトしました。',
            serverConnectionFailed: 'サーバーに接続できません。Goサーバーとngrokが実行されているか確認してください',
            loginFailed: 'ログイン失敗：',
            unknownError: '不明なエラー',
            wsUrlNotSet: 'まずコンソールで wsUrl を設定してください！',
            notReturned: '未返却',
            adminRequiredFields: 'アカウントIDとニックネームは必須項目です',
            adminPasswordRequired: '新規アカウント作成時はパスワードの設定が必要です',
            pushUnsupported: 'お使いのブラウザはプッシュ通知に対応していません',
            pushPermissionRequired: '返却通知を受け取るには通知権限が必要です',
            pushSubscribeSuccess: '購読に成功しました。本が返却されるとブラウザ通知を受け取れます。',
            pushSubscribeFailed: '購読リクエストに失敗しました。しばらくしてからもう一度お試しください。',
            pushUnexpectedError: 'エラーが発生し、購読を完了できませんでした。'
        },
        footer: {
            recommendation: '※ 本サイトは標準ブラウザを利用するか、図書室の端末をご利用ください。',
            copyright: 'Copyright Reserved by NCCU History Department 2026'
        },
				status: {
            lendable: '貸出可',
            notLendable: '貸出不可',
            borrowed: '貸出中',
            available: '館内あり'
        },
				editBook: {
            title: '書籍データの編集',
                blacklistTitle: '利用禁止メモを編集',
            lendableShort: '貸出可 (1)',
            notLendableShort: '貸出不可 (0)',
            save: '変更を保存'
        },
    }
};

// 2. 建立 i18n 實體
const i18n = new VueI18n({
    locale: localStorage.getItem('lib_lang') || 'zh-Hant', 
    fallbackLocale: 'zh-Hant',
    messages,
});
